name: Build UZonMail Service

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: ui-src/yarn.lock
        
    - name: Install dependencies
      run: |
        cd ui-src
        yarn install
        
    - name: Build frontend
      run: |
        cd ui-src
        yarn build
        
    - name: Build backend
      run: |
        cd backend-src/UZonMailService
        dotnet publish -c Release -o ../../build/service-linux-x64 -r linux-x64 --self-contained false
        
    - name: Prepare directories
      run: |
        # 使用 PowerShell 方式创建目录，忽略已存在的错误
        New-Item -ItemType Directory -Path "build/service-linux-x64/public" -Force
        New-Item -ItemType Directory -Path "build/service-linux-x64/wwwroot" -Force
        New-Item -ItemType Directory -Path "build/service-linux-x64/Quartz" -Force
        Copy-Item -Path "backend-src/UZonMailService/Quartz/quartz-sqlite.sqlite3" -Destination "build/service-linux-x64/Quartz/quartz-sqlite.sqlite3" -Force
        
    - name: Copy frontend to backend
      run: |
        # 确保目标目录存在
        New-Item -ItemType Directory -Path "build/service-linux-x64/wwwroot" -Force
        Copy-Item -Path "ui-src/dist/spa/*" -Destination "build/service-linux-x64/wwwroot/" -Recurse -Force
        
    - name: Install 7zip
      run: choco install 7zip -y
      
    - name: Create package
      run: |
        $version = (Get-Item "build/service-linux-x64/UZonMailService.dll").VersionInfo.FileVersion
        7z a -tzip "build/uzonmail-service-linux-x64-$version.zip" "build/service-linux-x64/*"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: uzonmail-service-linux-x64
        path: build/uzonmail-service-linux-x64-*.zip
