name: Build UZonMail Service

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'yarn'
        cache-dependency-path: ui-src/yarn.lock
        
    - name: Install dependencies
      run: |
        cd ui-src
        yarn install
        
    - name: Build frontend
      run: |
        cd ui-src
        yarn build
        
    - name: Build backend
      run: |
        cd backend-src/UZonMailService
        dotnet publish -c Release -o ../../build/service-linux-x64 -r linux-x64 --self-contained false
        
    - name: Prepare directories
      run: |
        mkdir -p build/service-linux-x64/public
        mkdir -p build/service-linux-x64/wwwroot
        mkdir -p build/service-linux-x64/Quartz
        cp backend-src/UZonMailService/Quartz/quartz-sqlite.sqlite3 build/service-linux-x64/Quartz/
        
    - name: Copy frontend to backend
      run: |
        cp -r ui-src/dist/spa/* build/service-linux-x64/wwwroot/
        
    - name: Install 7zip
      run: choco install 7zip -y
      
    - name: Create package
      run: |
        $version = (Get-Item "build/service-linux-x64/UZonMailService.dll").VersionInfo.FileVersion
        7z a -tzip build/uzonmail-service-linux-x64-$version.zip build/service-linux-x64/*
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: uzonmail-service-linux-x64
        path: build/uzonmail-service-linux-x64-*.zip
